### ISSUE TITLE
Length of Encoding Vector

### ISSUE THREAD

**Issue by HildaNya** [josebeo2016/biosegment#3]
![image](https://github.com/user-attachments/assets/2e354a0e-0109-4d81-9c69-9ad9c9bff2f2)
Hi! I'm trying to tie the codebase back to the paper and am a little confused by the length of the segmentation encoding vector. According to Fig 1. from your paper (attached here), the segmentation encoding vector is of length n, where n is the number of frames. **Does this mean that n (and the length of the encoding vector) would be different, depending on the duration of audio samples?** 

When I was trying to reproduce your results, tsme's fit transform requires vectors of the same size. So I just chopped off longer vectors to make sure they are all the same size. Which works.

But in your demo ipynb file, there doesn't seem to be any chopping performed on the encoding vectors. So perhaps there's a better solution that I may have missed?

Thank you in advance! Great work!

**Comment by josebeo2016** [comment]
Hello @HildaNya 
In my work I cut the audio input into 64600 samples, which is same to the RawNet 2 baseline. You can refer to this [code](https://github.com/josebeo2016/BTS-Encoder-ASVspoof/blob/3c3437c65f5a4dca047096e0a7012d007748e00d/asvspoof2021/LA/wav2vec-bio/data_utils.py#L82) in the other repo. For tsme, I visualize the vector of segmentation encoding vectors after chopping, so that they are all same length.
